# This workflow will upload a Python Package using Twine when a release is created
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python#publishing-to-package-registries

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Upload Python Package

on:
  release:
    types: [published]

permissions:
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - run: echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."
    - run: echo "🐧 This job is now running on a ${{ runner.os }} server hosted by GitHub!"
    - run: echo "🔎 The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
    - run: echo "Building wheel from tag ${{ github.ref_name }}"
    - uses: actions/checkout@v4

    - name: Build and publish distribution 📦 to Test PyPI
      uses: JRubics/poetry-publish@v2.0
      with:
        python_version: "3.11.8"
        pypi_token: ${{ secrets.TEST_PYPI_API_TOKEN }}
        repository_name: "testpypi"
        repository_url: "https://test.pypi.org/legacy/"

    - name: Build and publish distribution 📦 to PyPI
      uses: JRubics/poetry-publish@v2.0
      with:
        python_version: "3.11.18"
        pypi_token: ${{ secrets.PYPI_API_TOKEN }}
